-- Create a table for storing contact form submissions
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.contacts enable row level security;

-- Allow anyone (anon) to insert data
create policy "Enable insert for all users"
  on public.contacts
  for insert
  to anon
  with check (true);

-- Allow authenticated users to view data (optional, for admin dashboard later)
create policy "Enable read access for authenticated users only"
  on public.contacts
  for select
  to authenticated
  using (true);

-- Create a table for storing internship applications
create table if not exists public.internship_applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  position text not null
);

-- Enable Row Level Security (RLS)
alter table public.internship_applications enable row level security;

-- Allow anyone (anon) to insert data
create policy "Enable insert for all users"
  on public.internship_applications
  for insert
  to anon
  with check (true);

-- Allow authenticated users to view data (optional, for admin dashboard later)
create policy "Enable read access for authenticated users only"
  on public.internship_applications
  for select
  to authenticated
  using (true);

-- Create a table for internship positions
create table if not exists public.internship_positions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  items text[] not null
);

-- Enable Row Level Security (RLS)
alter table public.internship_positions enable row level security;

-- Allow anyone (anon) to view positions
create policy "Enable read access for all users"
  on public.internship_positions
  for select
  to anon
  using (true);

-- Insert default data if empty
insert into public.internship_positions (title, items)
select 'Agentic Builder', ARRAY['Internship Program', 'Part-time', 'Full-time']
where not exists (select 1 from public.internship_positions where title = 'Agentic Builder');

insert into public.internship_positions (title, items)
select 'Backend', ARRAY['Python Developer', 'Node.js Developer', 'Go Developer']
where not exists (select 1 from public.internship_positions where title = 'Backend');

insert into public.internship_positions (title, items)
select 'Content / Marketing', ARRAY['Content Creator', 'Digital Marketing', 'Social Media Manager']
where not exists (select 1 from public.internship_positions where title = 'Content / Marketing');

insert into public.internship_positions (title, items)
select 'Data Science', ARRAY['Data Analyst', 'Data Engineer', 'Machine Learning Engineer']
where not exists (select 1 from public.internship_positions where title = 'Data Science');

insert into public.internship_positions (title, items)
select 'Graphic', ARRAY['Graphic Designer', 'Motion Graphics', 'Art Director']
where not exists (select 1 from public.internship_positions where title = 'Graphic');

insert into public.internship_positions (title, items)
select 'Meta', ARRAY['Metaverse Developer', '3D Modeler', 'Unity Developer']
where not exists (select 1 from public.internship_positions where title = 'Meta');

insert into public.internship_positions (title, items)
select 'NLP', ARRAY['NLP Engineer', 'Linguist', 'AI Researcher']
where not exists (select 1 from public.internship_positions where title = 'NLP');

insert into public.internship_positions (title, items)
select 'Sales', ARRAY['Sales Executive', 'Account Manager', 'Business Development']
where not exists (select 1 from public.internship_positions where title = 'Sales');

insert into public.internship_positions (title, items)
select 'Software Development', ARRAY['Full Stack Developer', 'Frontend Developer', 'Software Engineer']
where not exists (select 1 from public.internship_positions where title = 'Software Development');

insert into public.internship_positions (title, items)
select 'TTS/ASR', ARRAY['Speech Engineer', 'Audio Engineer', 'Signal Processing']
where not exists (select 1 from public.internship_positions where title = 'TTS/ASR');

insert into public.internship_positions (title, items)
select 'UX/UI', ARRAY['UX Researcher', 'UI Designer', 'Product Designer']
where not exists (select 1 from public.internship_positions where title = 'UX/UI');

insert into public.internship_positions (title, items)
select 'Web App', ARRAY['React Developer', 'Vue Developer', 'Angular Developer']
where not exists (select 1 from public.internship_positions where title = 'Web App');

